### ISSUE TITLE
Add UDP packet header Information field to IPC

### ISSUE THREAD

**Issue by ulrikpedersen** [percival-detector/framereceiver#21]
The mezzanine board protocol specify an "Information" field (was originally 14 bytes - have grown larger in the latest draft of the protocol). This field contain data from the HW which must be stored along with the image data in the output file. 

Thus we need to add the "Information" data to the IPC transfer, either in:
- The ZMQ+JSON frame ready message.
- The SHM buffer.

Question: do the Mezzanine FW implement this "Information" field in the UDP packet header at the moment? I'm guessing it does not - so we don't need this for our Version0 delivery milestone...

**Comment by timcnicholls** [comment]
I think the appropriate place of this is in the SHM buffer rather than the frame ready notification. 

However, there is a more fundamental consideration: there is an information field per packet rather than e.g. per frame. Do we need to transfer all of them? Will they change from packet to packet, or just frame to frame? If the former, I propose we modify the SHM buffer structure to store the packet header as well as the payload (q.v. today's Slack discussion on buffer structure :wink:) , then the processor/file writer can parse/ignore/strip them off at will. If the info field doesn't change between frames we could copy the field into the buffer header for the first packet seen for instance.

**Comment by ulrikpedersen** [comment]
The purpose of the information field is to transfer signals (or small amount of data) from the HW on a per-frame basis: the main example is an event-ID.

We just designed the protocol to not have a frame-header (it could be dangerous if that is in a packet which is dropped in transfer) and as a pragmatic alternative just agreed to pass the few bytes of "Information" data along in the packet header.

I agree: we should modify the SHM FrameHeader to include this Information field. It can be copied from the first received packet as it should not change within a frame.

**Comment by timcnicholls** [comment]
That's fine, confirms what I was expecting. I'll add this feature for the version 0 delivery.
